version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-central-1
    volumes:
      - "./localstack:/var/lib/localstack"

  kafka:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_db
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      localstack:
        condition: service_started
      kafka:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      AWS_ENDPOINT: http://localstack:4566
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spring_db
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: spring

      # keep retrying DB instead of failing immediately
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: "60000"
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "30000"
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: "600000"

volumes:
  mysql-data: